### PR TITLE
Update Logo

### PR DESCRIPTION
**Pull request by maxwxyz**
@HarryvL I've recreated the logo as true SVG file and added text to distinguish between fcVM and fcSC.
grafik

### CODE REVIEW

**Comment by maxwxyz** [comment]
@HarryvL ping

**Comment by HarryvL** [comment]
Is there an action on me?

**Comment by maxwxyz** [comment]
@HarryvL yes, merge if you like it :)

**Comment by HarryvL** [comment]
I merged the version with the fcSC text. This one has no text. Is it your proposal to remove the text again?

**Comment by maxwxyz** [comment]
@HarryvL no this has the "fcVM" text: https://github.com/HarryvL/fcVM-workbench/pull/2/files

**Comment by maxwxyz** [comment]
any news? Shall I do something?

**Comment by HarryvL** [comment]
Looks good. I merged.

**Pull request merged**
